In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
np.random.seed(0)
pd.options.display.max_columns = 500
pd.options.display.max_rows = 999

In [2]:
df_train = pd.read_csv("C2T1Data//C2T1_Train.csv")
df_train = df_train.replace({'?':np.nan})

In [3]:
df_train

,encounter_id2,patient_nbr2,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,5283,48330653,Caucasian,Female,[80-90),NaN,2,1,4,13,NaN,NaN,68,2,28,0,0,0,398,427,38,8,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
1,8499,63555809,Caucasian,Female,[90-100),NaN,3,3,4,12,NaN,InternalMedicine,33,3,18,0,0,0,434,198,486,8,None,None,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
2,9441,42519137,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
3,20997,89868902,AfricanAmerican,Female,[40-50),NaN,1,1,7,9,NaN,NaN,47,2,17,0,0,0,250.7,403,996,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
4,28515,82637321,Caucasian,Male,[50-60),NaN,2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90761,443840309,100162346,AfricanAmerican,Male,[70-80),NaN,1,3,7,3,MC,NaN,51,0,16,0,0,0,250.13,291,458,9,None,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
90762,443840543,74694092,AfricanAmerican,Female,[80-90),NaN,1,4,5,5,MC,NaN,33,3,18,0,0,1,560,276,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
90763,443846909,41088659,Caucasian,Male,[70-80),NaN,1,1,7,1,MC,NaN,53,0,9,1,0,0,38,590,296,13,None,None,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
90764,443849927,31693541,Caucasian,Female,[80-90),NaN,2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,None,None,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
90765,443859983,175429180,Caucasian,Male,[70-80),NaN,1,1,7,6,NaN,NaN,13,3,3,0,0,0,530,530,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO

In [4]:
def missing_values_table(df_train):
        mis_val = df_train.isnull().sum()
        mis_val_percent = 100 * df_train.isnull().sum() / len(df_train)
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        print ("Your selected dataframe has " + str(df_train.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        return mis_val_table_ren_columns
missing_values_table(df_train)

Your selected dataframe has 50 columns.
There are 7 columns that have missing values.

                   Missing Values  % of Total Values
weight                      87840               96.8
medical_specialty           43674               48.1
payer_code                  38730               42.7
race                         2207                2.4
diag_3                       1357                1.5
diag_2                        336                0.4
diag_1                         17                0.0

In [5]:
#removing every column with more than 40% of missing values
df_train = df_train.drop(columns=['weight', 'medical_specialty', 'payer_code'])

In [6]:
#removing the rows that have missing values in column 'race'
df_train = df_train.dropna(subset=['race', 'diag_3', 'diag_1', 'diag_2'])

In [7]:
#replacing values in columns to a legit string to avoid any errors
df_train.A1Cresult = df_train.A1Cresult.replace({'>8':'Greater than 8', '>7':'Greater than 7'})

In [8]:
df_train.gender.value_counts()

Female             46955
Male               40239
Unknown/Invalid        1
Name: gender, dtype: int64

In [9]:
#removing the Undknow/Invalid enter in the gender #it would have been of no use!
df_train = df_train[df_train.gender != 'Unknown/Invalid']

In [10]:
#convert values starting with 'V' and 'E' to a numeric value so that Binning can be used on the whole column in diag_1
df_train.loc[df_train['diag_1'].str.contains('V',na=False), 'diag_1'] = 1000
df_train.loc[df_train['diag_1'].str.contains('E',na=False), 'diag_1'] = 1300
df_train.diag_1.value_counts()

428       6001
414       5836
786       3523
410       3183
486       3012
427       2403
491       1910
715       1809
434       1793
682       1783
780       1743
996       1725
276       1642
1000      1436
38        1436
250.8     1407
599       1384
584       1291
250.6     1050
518        945
577        915
820        909
493        872
435        861
562        841
574        818
250.7      764
296        762
440        750
560        745
433        695
998        662
250.13     630
722        627
578        556
507        539
250.02     532
789        488
530        467
453        461
403        434
250.11     432
8          430
535        412
402        404
295        390
415        378
997        375
162        373
458        371
724        361
250.82     354
250.12     338
285        320
733        310
278        306
401        302
590        298
592        295
482        292
280        280
197        277
558        276
153        269
824        258
569        250
426        245
571        240
511        235
404        232
648        230
250.1      228
531        228
250.4      225
411        223
787        222
466        214
707        213
198        212
572        210
552        197
575        193
532        191
812        190
730        186
600        177
436        166
331        165
250        165
250.81     162
557        158
424        156
431        153
540        151
721        147
805        141
618        140
185        139
348        136
784        133
444        133
250.22     133
564        130
174        126
790        126
386        124
536        123
553        122
821        116
441        115
398        115
515        115
728        114
218        113
808        112
189        110
413        109
250.03     107
823        105
157        103
345         98
537         97
681         95
250.2       95
188         95
292         95
294         94
182         93
443         91
781         90
593         90
785         89
211         89
729         89
852         88
202         88
576         87
250.41      86
437         83
154         82
250.83      82
288         81
459         81
654         80
487         80
291         79
595         79
455         79
290         78
432         78
274         78
726         77
300         76
438         75
250.42      75
490         74
287         73
425         73
79          70
566         68
723         67
346         66
585         65
995         65
782         65
626         65
807         64
813         63
416         62
711         62
481         61
496         60
799         60
112         60
284         59
423         57
642         57
282         56
303         56
420         55
238         54
625         53
567         53
716         53
608         52
298         52
447         51
738         51
151         51
550         50
155         49
332         48
969         48
293         47
311         47
962         47
965         47
241         47
250.92      46
719         46
924         46
53          46
512         43
850         43
286         43
555         42
596         42
253         42
227         42
275         41
191         41
70          41
465         41
556         40
220         39
727         37
573         37
514         37
225         37
822         37
714         37
9           36
922         35
42          35
340         34
620         34
421         34
203         34
519         34
959         34
451         33
429         33
788         33
442         33
485         32
860         32
239         31
568         30
851         30
333         30
516         30
304         29
309         29
183         29
604         29
611         29
492         28
250.23      28
659         28
510         27
277         27
349         26
802         26
430         25
47          25
710         25
999         25
396         24
351         24
233         24
193         24
250.01      23
196         23
135         23
783         23
644         23
478         23
205         23
844         23
801         23
522         23
658         23
534         22
250.43      22
255         22
794         21
283         21
204         21
661         21
614         21
456         21
150         20
621         20
235         20
607         20
494         20
327         20
252         19
446         19
307         19
281         19
338         19
242         19
586         19
581         18
357         18
305         18
527         18
250.33      18
461         18
533         17
617         17
656         17
473         17
616         17
958         17
250.3       17
967         16
920         16
591         16
289         16
380         16
664         16
825         16
528         16
250.32      15
513         15
693         15
312         15
873         15
156         15
601         15
972         15
480         15
200         15
853         14
355         14
226         14
627         13
251         13
250.31      13
756         13
152         13
840         13
199         13
358         13
652         13
594         13
867         12
718         12
378         12
171         12
297         12
263         12
244         11
376         11
457         11
250.93      11
250.21      11
977         11
565         11
725         11
680         11
3           11
847         11
843         11
966         11
350         10
201         10
736         10
892         10
35          10
891         10
368         10
989         10
161         10
695         10
935         10
521          9
646          9
454          9
54           9
335          9
310          9
945          9
462          9
705          9
816          9
588          9
158          9
933          9
660          9
78           9
394          9
882          9
11           8
968          8
383          8
195          8
359          8
464          8
845          8
992          8
306          8
541          8
641          8
342          8
250.5        8
475          8
212          7
94           7
709          7
163          7
663          7
964          7
230          7
82           7
686          7
88           7
810          7
747          7
41           7
323          7
551          7
320          7
237          7
341          7
337          7
746          7
861          7
579          7
117          7
354          7
362          7
214          6
180          6
970          6
445          6
737          6
526          6
353          6
694          6
696          6
864          6
866          6
184          6
223          6
991          6
796          6
815          6
865          6
952          6
708          6
5            6
344          5
141          5
210          5
751          5
647          5
215          5
835          5
49           5
273          5
717          5
983          5
324          5
942          5
854          5
208          5
753          5
583          5
806          5
397          5
379          5
643          5
136          5
495          5
831          5
463          4
570          4
34           4
759          4
470          4
395          4
893          4
301          4
508          4
863          4
846          4
836          4
175          4
272          4
792          4
720          4
655          4
800          4
745          4
452          4
598          4
483          4
692          4
934          4
685          4
524          4
890          4
261          4
622          4
192          4
356          4
814          4
619          4
674          3
240          3
388          3
971          3
228          3
795          3
250.52       3
886          3
881          3
917          3
826          3
916          3
173          3
172          3
142          3
179          3
374          3
474          3
669          3
928          3
529          3
936          3
602          3
623          3
706          3
883          3
164          3
361          3
987          3
731          3
803          3
797          3
377          3
868          3
862          3
632          3
734          3
986          3
250.53       3
793          3
963          3
250.9        3
262          3
170          2
973          2
360          2
75           2
66           2
236          2
48           2
369          2
422          2
879          2
405          2
23           2
246          2
7            2
921          2
582          2
610          2
923          2
501          2
308          2
633          2
245          2
58           2
500          2
271          2
279          2
875          2
382          2
131          2
634          2
149          2
615          2
336          2
506          2
194          2
417          2
322          2
914          2
683          2
732          2
352          2
880          2
27           2
975          2
653          2
904          2
147          2
848          2
250.91       2
990          2
146          2
878          2
187          2
735          2
229          2
980          2
897          2
370          2
580          2
334          2
36           2
384          2
385          1
375          1
913          1
955          1
133          1
325          1
543          1
804          1
110          1
381          1
148          1
603          1
911          1
207          1
838          1
988          1
10           1
834          1
791          1
906          1
833          1
871          1
870          1
542          1
885          1
217          1
143          1
61           1
637          1
372          1
250.51       1
690          1
391          1
839          1
941          1
366          1
39           1
365          1
31           1
114          1
832          1
817          1
57           1
649          1
944          1
52           1
657          1
939          1
389          1
645          1
640          1
691          1
347          1
266          1
160          1
216          1
982          1
842          1
448          1
115          1
915          1
318          1
1300         1
471          1
314          1
827          1
145          1
373          1
219          1
703          1
919          1
704          1
994          1
477          1
684          1
Name: diag_1, dtype: int64

In [11]:
#convert values starting with 'V' and 'E' to a numeric value so that Binning can be used on the whole column in diag_2
df_train.loc[df_train['diag_2'].str.contains('V',na=False), 'diag_2'] = 1000
df_train.loc[df_train['diag_2'].str.contains('E',na=False), 'diag_2'] = 1300
df_train.diag_2.value_counts()

428       5756
276       5663
250       4886
427       4271
401       3248
599       2870
496       2819
414       2360
403       2306
411       2287
250.02    1754
707       1718
585       1655
1000      1529
584       1471
250.01    1376
491       1315
285       1292
425       1275
780       1265
682       1227
486       1226
518       1196
424        911
413        906
250.6      803
493        763
1300       630
305        592
786        558
280        517
998        487
410        477
511        463
785        460
38         423
996        393
571        362
272        361
197        352
440        350
560        349
162        349
577        344
295        342
41         337
997        336
788        335
453        304
789        304
574        297
578        297
648        292
402        288
287        279
198        274
426        265
530        255
799        253
278        245
303        243
70         240
438        231
730        228
250.41     217
342        210
790        204
250.03     202
591        200
492        192
196        186
250.8      176
112        175
787        175
404        174
536        171
535        171
8          169
250.92     169
434        166
784        163
733        161
396        160
507        160
569        154
202        153
263        153
284        148
304        148
250.4      147
296        147
250.82     146
515        140
710        137
348        135
294        131
562        130
300        129
433        129
244        128
250.7      123
722        122
458        122
724        121
590        111
781        109
204        104
728        104
715        103
593        101
135        101
286         98
340         97
250.13      94
466         94
331         94
995         93
415         93
412         93
153         92
482         92
416         91
292         89
250.42      87
444         86
242         85
250.12      85
250.81      82
558         82
719         81
567         80
729         78
157         78
203         78
435         76
576         75
581         75
564         74
572         72
553         70
42          70
293         70
443         69
731         68
250.11      68
357         66
311         65
805         65
592         65
456         64
437         63
250.51      63
288         63
782         62
344         62
250.5       60
291         60
397         59
277         59
255         58
595         56
568         54
301         54
596         53
205         53
575         51
250.52      50
721         50
459         49
723         47
465         46
794         46
309         46
290         46
820         46
189         45
337         45
211         45
490         43
573         41
625         41
154         41
552         40
345         40
282         40
218         39
808         39
332         39
253         39
289         38
711         38
512         37
557         37
807         36
531         36
349         35
250.83      35
250.43      34
812         34
250.22      34
481         34
441         34
873         34
398         33
600         32
681         32
275         32
999         32
150         32
714         31
618         31
473         30
451         29
429         29
155         29
362         29
478         28
519         28
455         28
642         27
327         26
446         26
53          26
516         26
185         25
620         25
532         25
250.53      25
94          24
274         24
924         24
537         24
447         24
626         23
151         23
174         23
79          23
436         23
738         22
802         22
420         22
386         21
358         20
368         20
680         20
726         20
783         20
611         20
850         19
614         19
920         19
583         19
252         19
601         19
394         19
616         18
432         18
556         18
566         18
727         18
813         18
250.93      18
753         17
312         17
283         17
298         17
201         17
824         17
821         17
736         17
319         16
421         16
238         16
617         16
487         16
250.1       16
138         16
346         16
338         15
442         15
746         15
716         15
555         15
281         15
200         14
156         14
333         14
423         14
550         14
745         14
431         13
852         13
261         13
183         13
958         13
696         13
570         13
262         12
607         12
840         12
378         12
250.2       12
199         12
462         12
152         12
514         11
756         11
792         11
335         11
359         11
191         11
40          11
718         11
260         10
517         10
510         10
54          10
356         10
860         10
905         10
867         10
737         10
279         10
241         10
693         10
382         10
823         10
485          9
233          9
816          9
717          9
741          9
494          9
117          9
709          9
881          9
314          9
565          8
608          8
825          8
627          8
188          8
540          8
250.91       8
706          8
273          8
461          8
750          8
251          8
354          8
34           8
317          8
959          8
705          8
324          7
883          7
923          7
528          7
922          7
619          7
208          7
845          7
861          7
250.9        7
758          7
220          7
365          7
533          7
9            6
684          6
791          6
579          6
454          6
452          6
646          6
369          6
508          6
796          6
882          6
836          6
586          6
712          6
524          6
172          6
713          6
266          6
621          6
910          6
969          5
594          5
225          5
747          5
322          5
299          5
692          5
892          5
297          5
847          5
495          5
647          5
227          5
457          5
694          5
380          5
513          5
343          5
110          5
588          5
480          5
323          5
934          5
686          5
307          4
310          4
851          4
868          4
250.21       4
336          4
430          4
31           4
793          4
320          4
250.33       4
831          4
989          4
604          4
759          4
701          4
214          4
810          4
652          4
521          4
907          4
136          4
360          4
891          4
522          4
644          4
698          4
598          4
725          4
258          4
921          4
306          4
864          4
623          4
250.32       4
389          4
806          4
919          3
500          3
239          3
933          3
837          3
870          3
742          3
844          3
27           3
405          3
250.23       3
972          3
470          3
862          3
664          3
217          3
826          3
245          3
383          3
659          3
822          3
193          3
751          3
501          3
376          3
377          3
991          3
527          3
308          3
909          3
422          3
11           3
131          3
373          3
372          3
355          3
351          3
352          2
75           2
853          2
259          2
463          2
474          2
341          2
815          2
228          2
869          2
542          2
872          2
965          2
865          2
141          2
477          2
379          2
269          2
464          2
695          2
661          2
484          2
656          2
945          2
992          2
814          2
911          2
240          2
622          2
543          2
610          2
691          2
952          2
171          2
215          2
634          2
649          2
801          2
645          2
448          2
472          2
755          2
842          2
918          2
603          2
395          2
226          2
483          2
78           2
906          2
246          2
602          2
866          2
685          1
754          1
703          1
683          1
250.31       1
990          1
350          1
137          1
347          1
962          1
529          1
670          1
916          1
871          1
232          1
179          1
506          1
302          1
908          1
658          1
271          1
843          1
927          1
520          1
180          1
832          1
223          1
364          1
947          1
7            1
944          1
894          1
52           1
114          1
893          1
46           1
974          1
388          1
833          1
884          1
702          1
912          1
880          1
615          1
123          1
35           1
663          1
534          1
325          1
140          1
523          1
381          1
182          1
250.3        1
130          1
955          1
913          1
212          1
734          1
797          1
975          1
316          1
846          1
460          1
968          1
977          1
863          1
374          1
475          1
915          1
795          1
88           1
917          1
963          1
173          1
980          1
268          1
748          1
942          1
811          1
195          1
580          1
186          1
164          1
270          1
163          1
366          1
66           1
256          1
953          1
967          1
665          1
800          1
5            1
654          1
Name: diag_2, dtype: int64

In [12]:
#applying binning to diag_1 by taking its float value into bin_diag and then binning in values of bin_diag in bin_diag_1
#binning intervals are selected from 
bins = [1, 140, 240, 280, 290, 320, 390, 460, 520, 580, 630, 680, 710, 740, 760, 780, 800, 1000, 1200, 1400]
df_train['bin_diag'] = df_train.diag_1.astype('float')
df_train['bin_diag2'] = df_train.diag_2.astype('float')
df_train['bin_diag_1'] = pd.cut(df_train['bin_diag'], bins=bins, right=False)
df_train['bin_diag_2'] = pd.cut(df_train['bin_diag2'], bins=bins, right=False)
df_train

,encounter_id2,patient_nbr2,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,bin_diag,bin_diag2,bin_diag_1,bin_diag_2
0,5283,48330653,Caucasian,Female,[80-90),2,1,4,13,68,2,28,0,0,0,398,427,38,8,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,398.00,427.0,"[390, 460)","[390, 460)"
1,8499,63555809,Caucasian,Female,[90-100),3,3,4,12,33,3,18,0,0,0,434,198,486,8,None,None,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,434.00,198.0,"[390, 460)","[140, 240)"
2,9441,42519137,Caucasian,Male,[40-50),1,1,7,1,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,197.00,157.0,"[140, 240)","[140, 240)"
3,20997,89868902,AfricanAmerican,Female,[40-50),1,1,7,9,47,2,17,0,0,0,250.7,403,996,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,250.70,403.0,"[240, 280)","[390, 460)"
4,28515,82637321,Caucasian,Male,[50-60),2,1,2,3,31,6,16,0,0,0,414,411,250,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,414.00,411.0,"[390, 460)","[390, 460)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90761,443840309,100162346,AfricanAmerican,Male,[70-80),1,3,7,3,51,0,16,0,0,0,250.13,291,458,9,None,Greater than 8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,250.13,291.0,"[240, 280)","[290, 320)"
90762,443840543,74694092,AfricanAmerican,Female,[80-90),1,4,5,5,33,3,18,0,0,1,560,276,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,560.00,276.0,"[520, 580)","[240, 280)"
90763,443846909,41088659,Caucasian,Male,[70-80),1,1,7,1,53,0,9,1,0,0,38,590,296,13,None,None,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,38.00,590.0,"[1, 140)","[580, 630)"
90764,443849927,31693541,Caucasian,Female,[80-90),2,3,7,10,45,2,21,0,0,1,996,285,998,9,None,None,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,996.00,285.0,"[800, 1000)","[280, 290)"
90765,443859983,175429180,Caucasian,Male,[70-80),1,1,7,6,13,3,3,0,0,0,530,530,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,530.00,530.0,"[520, 580)","[520, 580)"

In [13]:
#now labeling all of the categorical features/columns using sklearn library (LabelEncoder)
#better coding practice can be followed to implement the below code - I would optimize this after completing the code!

lb_make = LabelEncoder()
df_train['race_code'] = lb_make.fit_transform(df_train['race'])
df_train['gender_code'] = lb_make.fit_transform(df_train['gender'])
df_train['max_glu_serum_code'] = lb_make.fit_transform(df_train['max_glu_serum'])
df_train['age_code'] = lb_make.fit_transform(df_train['age'])
df_train['A1Cresult_code'] = lb_make.fit_transform(df_train['A1Cresult'])
df_train['insulin_code'] = lb_make.fit_transform(df_train['insulin'])
df_train['change_code'] = lb_make.fit_transform(df_train['change'])
df_train['diabetesMed_code'] = lb_make.fit_transform(df_train['diabetesMed'])
df_train['bin_diag_1_code'] = lb_make.fit_transform(df_train['bin_diag_1'])
df_train['bin_diag_2_code'] = lb_make.fit_transform(df_train['bin_diag_2'])
df_train['num_diag'] = df_train['number_diagnoses']
df_train

,encounter_id2,patient_nbr2,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,bin_diag,bin_diag2,bin_diag_1,bin_diag_2,race_code,gender_code,max_glu_serum_code,age_code,A1Cresult_code,insulin_code,change_code,diabetesMed_code,bin_diag_1_code,bin_diag_2_code,num_diag
0,5283,48330653,Caucasian,Female,[80-90),2,1,4,13,68,2,28,0,0,0,398,427,38,8,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,398.00,427.0,"[390, 460)","[390, 460)",2,0,2,8,2,2,0,1,6,6,8
1,8499,63555809,Caucasian,Female,[90-100),3,3,4,12,33,3,18,0,0,0,434,198,486,8,None,None,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,434.00,198.0,"[390, 460)","[140, 240)",2,0,2,9,2,2,0,1,6,1,8
2,9441,42519137,Caucasian,Male,[40-50),1,1,7,1,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,197.00,157.0,"[140, 240)","[140, 240)",2,1,2,4,2,2,0,1,1,1,5
3,20997,89868902,AfricanAmerican,Female,[40-50),1,1,7,9,47,2,17,0,0,0,250.7,403,996,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,250.70,403.0,"[240, 280)","[390, 460)",0,0,2,4,2,2,1,1,2,6,9
4,28515,82637321,Caucasian,Male,[50-60),2,1,2,3,31,6,16,0,0,0,414,411,250,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,414.00,411.0,"[390, 460)","[390, 460)",2,1,2,5,2,2,1,1,6,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90761,443840309,100162346,AfricanAmerican,Male,[70-80),1,3,7,3,51,0,16,0,0,0,250.13,291,458,9,None,Greater than 8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,250.13,291.0,"[240, 280)","[290, 320)",0,1,2,7,1,0,0,1,2,4,9
90762,443840543,74694092,AfricanAmerican,Female,[80-90),1,4,5,5,33,3,18,0,0,1,560,276,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,560.00,276.0,"[520, 580)","[240, 280)",0,0,2,8,2,2,1,1,8,2,9
90763,443846909,41088659,Caucasian,Male,[70-80),1,1,7,1,53,0,9,1,0,0,38,590,296,13,None,None,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,38.00,590.0,"[1, 140)","[580, 630)",2,1,2,7,2,0,0,1,0,9,13
90764,443849927,31693541,Caucasian,Female,[80-90),2,3,7,10,45,2,21,0,0,1,996,285,998,9,None,None,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,996.00,285.0,"[800, 1000)","[280, 290)",2,0,2,8,2,3,0,1,15,3,9
90765,443859983,175429180,Caucasian,Male,[70-80),1,1,7,6,13,3,3,0,0,0,530,530,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,530.00,530.0,"[520, 580)","[520, 580)",2,1,2,7,2,1,1,0,8,8,9

In [14]:
#df_train['truth_le'] = lb_make.fit_transform(df_train['readmitted'])
#df_train.truth_le.value_counts()

df_train['truth_le'] = df_train.readmitted.replace({'NO':'1', '>30':'3', '<30':'2'})
df_train.truth_le.value_counts()

1    46929
3    30372
2     9893
Name: truth_le, dtype: int64

In [15]:
df_train.truth_le = df_train.truth_le.astype('int32')

In [16]:
df_train

,encounter_id2,patient_nbr2,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,bin_diag,bin_diag2,bin_diag_1,bin_diag_2,race_code,gender_code,max_glu_serum_code,age_code,A1Cresult_code,insulin_code,change_code,diabetesMed_code,bin_diag_1_code,bin_diag_2_code,num_diag,truth_le
0,5283,48330653,Caucasian,Female,[80-90),2,1,4,13,68,2,28,0,0,0,398,427,38,8,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,398.00,427.0,"[390, 460)","[390, 460)",2,0,2,8,2,2,0,1,6,6,8,1
1,8499,63555809,Caucasian,Female,[90-100),3,3,4,12,33,3,18,0,0,0,434,198,486,8,None,None,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,434.00,198.0,"[390, 460)","[140, 240)",2,0,2,9,2,2,0,1,6,1,8,1
2,9441,42519137,Caucasian,Male,[40-50),1,1,7,1,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,197.00,157.0,"[140, 240)","[140, 240)",2,1,2,4,2,2,0,1,1,1,5,1
3,20997,89868902,AfricanAmerican,Female,[40-50),1,1,7,9,47,2,17,0,0,0,250.7,403,996,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,250.70,403.0,"[240, 280)","[390, 460)",0,0,2,4,2,2,1,1,2,6,9,3
4,28515,82637321,Caucasian,Male,[50-60),2,1,2,3,31,6,16,0,0,0,414,411,250,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,414.00,411.0,"[390, 460)","[390, 460)",2,1,2,5,2,2,1,1,6,6,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90761,443840309,100162346,AfricanAmerican,Male,[70-80),1,3,7,3,51,0,16,0,0,0,250.13,291,458,9,None,Greater than 8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,250.13,291.0,"[240, 280)","[290, 320)",0,1,2,7,1,0,0,1,2,4,9,3
90762,443840543,74694092,AfricanAmerican,Female,[80-90),1,4,5,5,33,3,18,0,0,1,560,276,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,560.00,276.0,"[520, 580)","[240, 280)",0,0,2,8,2,2,1,1,8,2,9,1
90763,443846909,41088659,Caucasian,Male,[70-80),1,1,7,1,53,0,9,1,0,0,38,590,296,13,None,None,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,38.00,590.0,"[1, 140)","[580, 630)",2,1,2,7,2,0,0,1,0,9,13,1
90764,443849927,31693541,Caucasian,Female,[80-90),2,3,7,10,45,2,21,0,0,1,996,285,998,9,None,None,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,996.00,285.0,"[800, 1000)","[280, 290)",2,0,2,8,2,3,0,1,15,3,9,1
90765,443859983,175429180,Caucasian,Male,[70-80),1,1,7,6,13,3,3,0,0,0,530,530,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,530.00,530.0,"[520, 580)","[520, 580)",2,1,2,7,2,1,1,0,8,8,9,1

In [17]:
new_df = pd.concat((df_train.iloc[:,5:15], df_train.iloc[:, 51:62]), axis = 1)
df_col_fnl = new_df.columns
trial_two = new_df.copy()
df_col_fnl #not the best of the naming conventions - but its okay, we don't need this much.

Index(['admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'race_code', 'gender_code', 'max_glu_serum_code',
       'age_code', 'A1Cresult_code', 'insulin_code', 'change_code',
       'diabetesMed_code', 'bin_diag_1_code', 'bin_diag_2_code', 'num_diag'],
      dtype='object')

In [18]:
trial_two

,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,race_code,gender_code,max_glu_serum_code,age_code,A1Cresult_code,insulin_code,change_code,diabetesMed_code,bin_diag_1_code,bin_diag_2_code,num_diag
0,2,1,4,13,68,2,28,0,0,0,2,0,2,8,2,2,0,1,6,6,8
1,3,3,4,12,33,3,18,0,0,0,2,0,2,9,2,2,0,1,6,1,8
2,1,1,7,1,51,0,8,0,0,0,2,1,2,4,2,2,0,1,1,1,5
3,1,1,7,9,47,2,17,0,0,0,0,0,2,4,2,2,1,1,2,6,9
4,2,1,2,3,31,6,16,0,0,0,2,1,2,5,2,2,1,1,6,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90761,1,3,7,3,51,0,16,0,0,0,0,1,2,7,1,0,0,1,2,4,9
90762,1,4,5,5,33,3,18,0,0,1,0,0,2,8,2,2,1,1,8,2,9
90763,1,1,7,1,53,0,9,1,0,0,2,1,2,7,2,0,0,1,0,9,13
90764,2,3,7,10,45,2,21,0,0,1,2,0,2,8,2,3,0,1,15,3,9
90765,1,1,7,6,13,3,3,0,0,0,2,1,2,7,2,1,1,0,8,8,9

In [19]:
labels = np.array(df_train['truth_le'])
labels

array([1, 1, 1, ..., 1, 1, 1])

In [20]:
features_list = list(trial_two.columns)
features_list

['admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'race_code',
 'gender_code',
 'max_glu_serum_code',
 'age_code',
 'A1Cresult_code',
 'insulin_code',
 'change_code',
 'diabetesMed_code',
 'bin_diag_1_code',
 'bin_diag_2_code',
 'num_diag']

In [21]:
trial_two = np.array(trial_two)

In [35]:
train_features, test_features, train_labels, test_labels = train_test_split(trial_two, labels, test_size = 0.25, random_state = 100, stratify = labels)

In [23]:
train_features

array([[ 3,  1,  1, ...,  8,  7,  9],
       [ 1,  3,  7, ..., 16,  2,  9],
       [ 3,  3,  1, ...,  2, 12,  9],
       ...,
       [ 5,  3,  1, ...,  6,  7,  9],
       [ 1,  3,  7, ...,  2,  6,  9],
       [ 3,  1,  1, ...,  6,  6,  9]], dtype=int64)

In [24]:
test_features.shape

(21799, 21)

In [25]:
train_labels.shape

(65395,)

In [26]:
test_labels.shape

(21799,)

In [36]:
#Train the random forest classifier
rand_clas = RandomForestClassifier(n_jobs=2, random_state=0, n_estimators=100, bootstrap = True)
rand_clas.fit(train_features, train_labels)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [28]:
rand_clas.predict(test_features)

array([1, 1, 1, ..., 3, 3, 1])

In [37]:
predictions = rand_clas.predict(test_features)

In [30]:
#predictions = rand_clas.predict(train_features)
#predictions.shape

In [38]:
errors = abs(predictions - test_labels)
print('Mean Absolute Error:', round(np.mean(errors), 2), '??')

Mean Absolute Error: 0.73 ??

In [32]:
#performance matrics
#mape = 100* (errors/test_labels)
#accuracy = 100- np.mean(mape)

#print('Accuracy:', round(accuracy, 2), '%')

In [42]:
pd.crosstab(test_labels, predictions, rownames=['Actual'], colnames=['Predicted'])

Predicted     1   2     3
Actual
1          9718  28  1987
2          1482  61   930
3          4685  70  2838

In [41]:
precision_recall_fscore_support(test_labels, predictions, average='weighted')

(0.5445693796038367, 0.5787880177989816, 0.5321549595227049, None)